apiVersion: v1
kind: Service
metadata:
  name: my-pod-service
spec:
  type: LoadBalancer
  selector:
    app: my-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-pod
spec:
  replicas: 1  # adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: main
          image: hitedemiore/mainapp
          ports:
            - containerPort: 80
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
        - name: sidecar
          image: hitedemiore/sidecard
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "[ \"$HEALTH_STATUS\" = 'healthy' ]"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
